#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo service nginx start
