#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get update
apt-get install haproxy

cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend myfrontend
  bind *:80
  default_backend myservers

backend myservers
  balance roundrobin
  server 405012-web-01 100.25.144.173:80
  server 405012-web-02 54.160.65.154:80
EOL
update-rc.d haproxy defaults
service haproxy start
