#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it
password="$1"
mysqldump -u root -p "${password}" --all-databases > backup.sql
timestamp=$(date +%d-%m-%Y)
tar -cvzf "${timestamp}.tar.gz" backup.sql
