#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and 
# terminates itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"
echo $$ > $pid_file


handle_term() {
	echo "I hate the kill command"
	rm "$pid_file"
	exit 1
}

trap 'handle_term' TERM

handle_int() {
	echo "Y U no love me?!"
	exit 1
}

trap 'handle_int' INT

handle_term_quit() {
	rm $pid_file
	exit 0
}

trap 'handle_term_quit' QUIT

while true
do
        echo "To infinity and beyond"
	sleep 1
done

