#!/usr/bin/env bash
# Manages manage_my_process
process_name="manage_my_process"
pid_file="/var/run/my_process.pid"

start() {
	if [ ! -f "$pid_file" ]
	then
		./manage_my_process &
		echo "$!" > "$pid_file"
		echo "$process_name started"
	fi
}

stop() {
	pid=$(cat "$pid_file")
	kill "$pid"
	rm "$pid_file"
	echo "$process_name stopped"
}

restart() {
	if [ -f "$pid_file" ]
	then
		stop
	fi
	start
	echo "$process_name restarted"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
	
exit 0
