#!/usr/bin/env bash
# Manages manage_my_process
process_name="manage_my_process"
pid_file="/var/run/my_process.pid"
start() {
	echo "$!" > "$pid_file"
	echo "manage_my_process started"
}

stop() {
	pid=$(cat "$pid_file")
	killall "$process_name"
	rm "$pid_file"
	echo "manage_my_process stopped"
}

restart() {
	stop
	start
	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
	
exit 0
