#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
while read -r line;
do
	username=$(echo "$line" | cut -d: -f1)
	userid=$(echo "$line" | cut -d: -f3)
	homepath=$(echo "$line" | cut -d: -f6)
	echo "$username:$userid:$homepath"
done < "/etc/passwd"
