#!/usr/bin/env bash
# This script displays bad luck for the 4th loop iteration
# good luck for the 8th loop iteration
# Best School for the other iterations
i=1
while [[ $i -le 10 ]];
do
	(( i += 1))
	if [ $i -eq 5 ]
	then
		echo "bad luck"
	elif [ $i -eq 9 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
