#!/usr/bin/env bash
# configures an Ubuntu server
cp /etc/hosts copy
sed -i "s/.*localhost$/127.0.0.2 localhost/" copy
if grep -q ".*facebook.com$" copy
then
	sed -i "s/.*facebook.com$/8.8.8.8 facebook.com/" copy
else
	echo "8.8.8.8 facebook.com" >> copy
fi
cp -f copy /etc/hosts
rm copy
