#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
chown -R nginx:nginx /var/lib/nginx /var/log/nginx
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/nginx.conf
sed -i 's/server {listen 443 ssl;/server {listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
